services:
  app:
    container_name: next14_pg_start_app
    build:
      context: .
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    environment:
      WATCHPACK_POLLING: true
      DATABASE_URL: ${DATABASE_URL}
    command: npm run dev
    # command: sh -c "npm run dev"
    networks:
      - app_network
    depends_on:
      - db
  db:
    container_name: next14_pg_start_db
    image: postgres:16
    hostname: db
    env_file:
      - .env
    networks:
      - app_network
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
networks:
  app_network:
    driver: bridge
volumes:
  pgdata:
  node-modules:
