services:
  app:
    build:
      context: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
